using NpgsqlTypes;

namespace Platform.Data;

public sealed class UserProfile
{
    public Guid Id { get; init; }

    public required string Username { get; init; }

    public required string Email { get; init; }

    public required string DisplayName { get; init; }

    public required string Role { get; init; }

    public Guid SiteId { get; init; }

    public Site? Site { get; init; }

    public Guid DepartmentId { get; init; }

    public Department? Department { get; init; }

    /// <summary>
    /// Generated by Postgres over the name, username and email; the GIN index on it is what makes global
    /// search (WP-5.4) find a person. Never assigned in C# — the database owns the value.
    /// </summary>
    public NpgsqlTsVector SearchVector { get; init; } = null!;
}