// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Helpdesk.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Helpdesk.Data.Migrations
{
    [DbContext(typeof(HelpdeskDbContext))]
    [Migration("20260806223635_WP15_SlaEngine")]
    partial class WP15_SlaEngine
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("helpdesk")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Helpdesk.Data.BusinessHoursCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.Property<int>("WorkingDays")
                        .HasColumnType("integer")
                        .HasColumnName("working_days");

                    b.HasKey("Id")
                        .HasName("pk_business_hours_calendars");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_business_hours_calendars_name");

                    b.ToTable("business_hours_calendars", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.SlaPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("calendar_id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("priority");

                    b.Property<int>("ResolutionTargetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("resolution_target_minutes");

                    b.Property<int>("ResponseTargetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("response_target_minutes");

                    b.Property<int>("WarningPercent")
                        .HasColumnType("integer")
                        .HasColumnName("warning_percent");

                    b.HasKey("Id")
                        .HasName("pk_sla_policies");

                    b.HasIndex("CalendarId")
                        .HasDatabaseName("ix_sla_policies_calendar_id");

                    b.HasIndex("Priority", "Category", "IsActive")
                        .HasDatabaseName("ix_sla_policies_priority_category_is_active");

                    b.ToTable("sla_policies", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_name");

                    b.ToTable("teams", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TeamMember", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("TechnicianId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("technician_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.HasKey("TeamId", "TechnicianId")
                        .HasName("pk_team_members");

                    b.ToTable("team_members", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignedTechnicianId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("assigned_technician_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("description");

                    b.Property<string>("Impact")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("impact");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("priority");

                    b.Property<Guid?>("QueueId")
                        .HasColumnType("uuid")
                        .HasColumnName("queue_id");

                    b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("requester_id");

                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("SequenceNumber"));

                    b.Property<Guid>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("10000000-0000-0000-0000-000000000001"))
                        .HasColumnName("status_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("urgency");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("AssignedTechnicianId")
                        .HasDatabaseName("ix_tickets_assigned_technician_id");

                    b.HasIndex("QueueId")
                        .HasDatabaseName("ix_tickets_queue_id");

                    b.HasIndex("SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_tickets_sequence_number");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_tickets_status_id");

                    b.ToTable("tickets", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketAssignmentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_id");

                    b.Property<string>("FromTechnicianId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("from_technician_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("QueueId")
                        .HasColumnType("uuid")
                        .HasColumnName("queue_id");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<string>("ToTechnicianId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("to_technician_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_assignment_history");

                    b.HasIndex("QueueId")
                        .HasDatabaseName("ix_ticket_assignment_history_queue_id");

                    b.HasIndex("TicketId", "OccurredAt")
                        .HasDatabaseName("ix_ticket_assignment_history_ticket_id_occurred_at");

                    b.ToTable("ticket_assignment_history", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("object_key");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<string>("UploadedById")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("uploaded_by_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_attachments");

                    b.HasIndex("ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_attachments_object_key");

                    b.HasIndex("TicketId", "CreatedAt")
                        .HasDatabaseName("ix_ticket_attachments_ticket_id_created_at");

                    b.ToTable("ticket_attachments", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_internal");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_comments");

                    b.HasIndex("TicketId", "CreatedAt")
                        .HasDatabaseName("ix_ticket_comments_ticket_id_created_at");

                    b.ToTable("ticket_comments", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastAssignedTechnicianId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_assigned_technician_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_queues");

                    b.HasIndex("TeamId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_queues_team_id_name");

                    b.ToTable("ticket_queues", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketSla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("AccumulatedBusinessSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("accumulated_business_seconds");

                    b.Property<DateTimeOffset?>("ActiveSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("active_since");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<bool>("ResolutionBreached")
                        .HasColumnType("boolean")
                        .HasColumnName("resolution_breached");

                    b.Property<DateTimeOffset?>("ResolutionCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolution_completed_at");

                    b.Property<bool>("ResolutionWarningRaised")
                        .HasColumnType("boolean")
                        .HasColumnName("resolution_warning_raised");

                    b.Property<bool>("ResponseBreached")
                        .HasColumnType("boolean")
                        .HasColumnName("response_breached");

                    b.Property<double?>("ResponseBusinessSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("response_business_seconds");

                    b.Property<DateTimeOffset?>("ResponseCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("response_completed_at");

                    b.Property<bool>("ResponseWarningRaised")
                        .HasColumnType("boolean")
                        .HasColumnName("response_warning_raised");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_slas");

                    b.HasIndex("PolicyId")
                        .HasDatabaseName("ix_ticket_slas_policy_id");

                    b.HasIndex("TicketId")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_slas_ticket_id");

                    b.ToTable("ticket_slas", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresResolutionNote")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_resolution_note");

                    b.HasKey("Id")
                        .HasName("pk_ticket_statuses");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_statuses_name");

                    b.ToTable("ticket_statuses", "helpdesk");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            DisplayOrder = 1,
                            Name = "New",
                            RequiresResolutionNote = false
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            DisplayOrder = 2,
                            Name = "Triage",
                            RequiresResolutionNote = false
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            DisplayOrder = 3,
                            Name = "InProgress",
                            RequiresResolutionNote = false
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            DisplayOrder = 4,
                            Name = "Pending",
                            RequiresResolutionNote = false
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            DisplayOrder = 5,
                            Name = "Resolved",
                            RequiresResolutionNote = true
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            DisplayOrder = 6,
                            Name = "Closed",
                            RequiresResolutionNote = false
                        });
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketStatusTransition", b =>
                {
                    b.Property<Guid>("FromStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_status_id");

                    b.Property<Guid>("ToStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_status_id");

                    b.HasKey("FromStatusId", "ToStatusId")
                        .HasName("pk_ticket_status_transitions");

                    b.HasIndex("ToStatusId")
                        .HasDatabaseName("ix_ticket_status_transitions_to_status_id");

                    b.ToTable("ticket_status_transitions", "helpdesk");

                    b.HasData(
                        new
                        {
                            FromStatusId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ToStatusId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            FromStatusId = new Guid("10000000-0000-0000-0000-000000000002"),
                            ToStatusId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            FromStatusId = new Guid("10000000-0000-0000-0000-000000000003"),
                            ToStatusId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            FromStatusId = new Guid("10000000-0000-0000-0000-000000000004"),
                            ToStatusId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            FromStatusId = new Guid("10000000-0000-0000-0000-000000000004"),
                            ToStatusId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            FromStatusId = new Guid("10000000-0000-0000-0000-000000000005"),
                            ToStatusId = new Guid("10000000-0000-0000-0000-000000000006")
                        });
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketTransitionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("FromStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_status_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("resolution_note");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<Guid>("ToStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_status_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_transition_history");

                    b.HasIndex("FromStatusId")
                        .HasDatabaseName("ix_ticket_transition_history_from_status_id");

                    b.HasIndex("ToStatusId")
                        .HasDatabaseName("ix_ticket_transition_history_to_status_id");

                    b.HasIndex("TicketId", "OccurredAt")
                        .HasDatabaseName("ix_ticket_transition_history_ticket_id_occurred_at");

                    b.ToTable("ticket_transition_history", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketWorklog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("author_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Minutes")
                        .HasColumnType("integer")
                        .HasColumnName("minutes");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_worklogs");

                    b.HasIndex("TicketId", "CreatedAt")
                        .HasDatabaseName("ix_ticket_worklogs_ticket_id_created_at");

                    b.ToTable("ticket_worklogs", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.SlaPolicy", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.BusinessHoursCalendar", "Calendar")
                        .WithMany()
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sla_policies_business_hours_calendars_calendar_id");

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TeamMember", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_members_teams_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.Ticket", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.TicketQueue", "Queue")
                        .WithMany()
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tickets_ticketqueues_queue_id");

                    b.HasOne("Modules.Helpdesk.Data.TicketStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_ticket_statuses_status_id");

                    b.Navigation("Queue");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketAssignmentHistory", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.TicketQueue", "Queue")
                        .WithMany()
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_assignment_history_ticketqueues_queue_id");

                    b.HasOne("Modules.Helpdesk.Data.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_assignment_history_tickets_ticket_id");

                    b.Navigation("Queue");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketAttachment", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_attachments_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketComment", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_comments_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketQueue", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_queues_teams_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketSla", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.SlaPolicy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_slas_sla_policies_policy_id");

                    b.HasOne("Modules.Helpdesk.Data.Ticket", "Ticket")
                        .WithOne()
                        .HasForeignKey("Modules.Helpdesk.Data.TicketSla", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_slas_tickets_ticket_id");

                    b.Navigation("Policy");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketStatusTransition", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.TicketStatus", "FromStatus")
                        .WithMany()
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_status_transitions_ticket_statuses_from_status_id");

                    b.HasOne("Modules.Helpdesk.Data.TicketStatus", "ToStatus")
                        .WithMany()
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_status_transitions_ticket_statuses_to_status_id");

                    b.Navigation("FromStatus");

                    b.Navigation("ToStatus");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketTransitionHistory", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.TicketStatus", "FromStatus")
                        .WithMany()
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_transition_history_ticket_statuses_from_status_id");

                    b.HasOne("Modules.Helpdesk.Data.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_transition_history_tickets_ticket_id");

                    b.HasOne("Modules.Helpdesk.Data.TicketStatus", "ToStatus")
                        .WithMany()
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_transition_history_ticket_statuses_to_status_id");

                    b.Navigation("FromStatus");

                    b.Navigation("Ticket");

                    b.Navigation("ToStatus");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketWorklog", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_worklogs_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.Team", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
