// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Helpdesk.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Helpdesk.Data.Migrations
{
    [DbContext(typeof(HelpdeskDbContext))]
    [Migration("20260806053215_WP12_StatusWorkflow")]
    partial class WP12_StatusWorkflow
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("helpdesk")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Helpdesk.Data.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("description");

                    b.Property<string>("Impact")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("impact");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("priority");

                    b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("requester_id");

                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("SequenceNumber"));

                    b.Property<Guid>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("10000000-0000-0000-0000-000000000001"))
                        .HasColumnName("status_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("urgency");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_tickets_sequence_number");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_tickets_status_id");

                    b.ToTable("tickets", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresResolutionNote")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_resolution_note");

                    b.HasKey("Id")
                        .HasName("pk_ticket_statuses");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_statuses_name");

                    b.ToTable("ticket_statuses", "helpdesk");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            DisplayOrder = 1,
                            Name = "New",
                            RequiresResolutionNote = false
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            DisplayOrder = 2,
                            Name = "Triage",
                            RequiresResolutionNote = false
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            DisplayOrder = 3,
                            Name = "InProgress",
                            RequiresResolutionNote = false
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            DisplayOrder = 4,
                            Name = "Pending",
                            RequiresResolutionNote = false
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            DisplayOrder = 5,
                            Name = "Resolved",
                            RequiresResolutionNote = true
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            DisplayOrder = 6,
                            Name = "Closed",
                            RequiresResolutionNote = false
                        });
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketStatusTransition", b =>
                {
                    b.Property<Guid>("FromStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_status_id");

                    b.Property<Guid>("ToStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_status_id");

                    b.HasKey("FromStatusId", "ToStatusId")
                        .HasName("pk_ticket_status_transitions");

                    b.HasIndex("ToStatusId")
                        .HasDatabaseName("ix_ticket_status_transitions_to_status_id");

                    b.ToTable("ticket_status_transitions", "helpdesk");

                    b.HasData(
                        new
                        {
                            FromStatusId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ToStatusId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            FromStatusId = new Guid("10000000-0000-0000-0000-000000000002"),
                            ToStatusId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            FromStatusId = new Guid("10000000-0000-0000-0000-000000000003"),
                            ToStatusId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            FromStatusId = new Guid("10000000-0000-0000-0000-000000000004"),
                            ToStatusId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            FromStatusId = new Guid("10000000-0000-0000-0000-000000000005"),
                            ToStatusId = new Guid("10000000-0000-0000-0000-000000000006")
                        });
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketTransitionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("FromStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_status_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("resolution_note");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<Guid>("ToStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_status_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_transition_history");

                    b.HasIndex("FromStatusId")
                        .HasDatabaseName("ix_ticket_transition_history_from_status_id");

                    b.HasIndex("ToStatusId")
                        .HasDatabaseName("ix_ticket_transition_history_to_status_id");

                    b.HasIndex("TicketId", "OccurredAt")
                        .HasDatabaseName("ix_ticket_transition_history_ticket_id_occurred_at");

                    b.ToTable("ticket_transition_history", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.Ticket", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.TicketStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_ticket_statuses_status_id");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketStatusTransition", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.TicketStatus", "FromStatus")
                        .WithMany()
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_status_transitions_ticket_statuses_from_status_id");

                    b.HasOne("Modules.Helpdesk.Data.TicketStatus", "ToStatus")
                        .WithMany()
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_status_transitions_ticket_statuses_to_status_id");

                    b.Navigation("FromStatus");

                    b.Navigation("ToStatus");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketTransitionHistory", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.TicketStatus", "FromStatus")
                        .WithMany()
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_transition_history_ticket_statuses_from_status_id");

                    b.HasOne("Modules.Helpdesk.Data.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_transition_history_tickets_ticket_id");

                    b.HasOne("Modules.Helpdesk.Data.TicketStatus", "ToStatus")
                        .WithMany()
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_transition_history_ticket_statuses_to_status_id");

                    b.Navigation("FromStatus");

                    b.Navigation("Ticket");

                    b.Navigation("ToStatus");
                });
#pragma warning restore 612, 618
        }
    }
}
