// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Helpdesk.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Modules.Helpdesk.Data.Migrations
{
    [DbContext(typeof(HelpdeskDbContext))]
    [Migration("20260817062131_WP59_KnowledgeBase")]
    partial class WP59_KnowledgeBase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("helpdesk")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Helpdesk.Data.AlertTicket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid")
                        .HasColumnName("alert_id");

                    b.Property<DateTimeOffset?>("AutoResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("auto_resolved_at");

                    b.Property<Guid>("CiId")
                        .HasColumnType("uuid")
                        .HasColumnName("ci_id");

                    b.Property<string>("DedupeKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("dedupe_key");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<DateTimeOffset>("FirstRaisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_raised_at");

                    b.Property<DateTimeOffset?>("LastClearedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_cleared_at");

                    b.Property<DateTimeOffset>("LastRaisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_raised_at");

                    b.Property<string>("LastSeverity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("last_severity");

                    b.Property<int>("OccurrenceCount")
                        .HasColumnType("integer")
                        .HasColumnName("occurrence_count");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rule_id");

                    b.Property<int>("SuppressedCount")
                        .HasColumnType("integer")
                        .HasColumnName("suppressed_count");

                    b.Property<int>("TicketCount")
                        .HasColumnType("integer")
                        .HasColumnName("ticket_count");

                    b.Property<DateTimeOffset?>("TicketCreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ticket_created_at");

                    b.Property<Guid?>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_alert_tickets");

                    b.HasIndex("DedupeKey")
                        .IsUnique()
                        .HasDatabaseName("ix_alert_tickets_dedupe_key");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_alert_tickets_device_id");

                    b.HasIndex("TicketCreatedAt")
                        .HasDatabaseName("ix_alert_tickets_ticket_created_at");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_alert_tickets_ticket_id");

                    b.ToTable("alert_tickets", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.BusinessHoursCalendar", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("end_time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time without time zone")
                        .HasColumnName("start_time");

                    b.Property<string>("TimeZoneId")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("time_zone_id");

                    b.Property<int>("WorkingDays")
                        .HasColumnType("integer")
                        .HasColumnName("working_days");

                    b.HasKey("Id")
                        .HasName("pk_business_hours_calendars");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_business_hours_calendars_name");

                    b.ToTable("business_hours_calendars", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.CannedResponse", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_canned_responses");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_canned_responses_name");

                    b.ToTable("canned_responses", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.KbArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ArchivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("archived_at");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("author_id");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("author_name");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)")
                        .HasColumnName("body");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Keywords")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("keywords");

                    b.Property<Guid?>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<DateTimeOffset?>("PublishedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("published_at");

                    b.Property<string>("PublishedById")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("published_by_id");

                    b.Property<string>("PublishedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("published_by_name");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("setweight(to_tsvector('english', coalesce(title, '')), 'A')\n|| setweight(to_tsvector('english', coalesce(summary, '')), 'B')\n|| setweight(to_tsvector('english', coalesce(keywords, '')), 'B')\n|| setweight(to_tsvector('english', coalesce(body, '')), 'C')", true);

                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedById")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by_id");

                    b.Property<string>("UpdatedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by_name");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_kb_articles");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_kb_articles_category_id");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_kb_articles_problem_id");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_kb_articles_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_kb_articles_sequence_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_kb_articles_status");

                    b.ToTable("kb_articles", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.KbArticleRevision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("author_id");

                    b.Property<string>("AuthorName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("author_name");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(50000)
                        .HasColumnType("character varying(50000)")
                        .HasColumnName("body");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Keywords")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("keywords");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("summary");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_kb_article_revisions");

                    b.HasIndex("ArticleId", "Version")
                        .IsUnique()
                        .HasDatabaseName("ix_kb_article_revisions_article_id_version");

                    b.ToTable("kb_article_revisions", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.Problem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignedTechnicianId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("assigned_technician_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid?>("CiId")
                        .HasColumnType("uuid")
                        .HasColumnName("ci_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset?>("KnownErrorAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("known_error_at");

                    b.Property<string>("OpenedById")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("opened_by_id");

                    b.Property<string>("OpenedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("opened_by_name");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("priority");

                    b.Property<string>("Resolution")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("resolution");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("RootCause")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("root_cause");

                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("SequenceNumber"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Workaround")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("workaround");

                    b.HasKey("Id")
                        .HasName("pk_problems");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_problems_category_id");

                    b.HasIndex("CiId")
                        .HasDatabaseName("ix_problems_ci_id");

                    b.HasIndex("SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_problems_sequence_number");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_problems_status");

                    b.ToTable("problems", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.ProblemIncident", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.Property<string>("LinkedById")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("linked_by_id");

                    b.Property<string>("LinkedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("linked_by_name");

                    b.Property<Guid>("ProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("problem_id");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_problem_incidents");

                    b.HasIndex("ProblemId")
                        .HasDatabaseName("ix_problem_incidents_problem_id");

                    b.HasIndex("TicketId")
                        .IsUnique()
                        .HasDatabaseName("ix_problem_incidents_ticket_id");

                    b.ToTable("problem_incidents", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.ProblemSuggestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<Guid?>("CiId")
                        .HasColumnType("uuid")
                        .HasColumnName("ci_id");

                    b.Property<Guid?>("CreatedProblemId")
                        .HasColumnType("uuid")
                        .HasColumnName("created_problem_id");

                    b.Property<DateTimeOffset>("DetectedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("detected_at");

                    b.Property<string>("DismissReason")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("dismiss_reason");

                    b.Property<int>("IncidentCount")
                        .HasColumnType("integer")
                        .HasColumnName("incident_count");

                    b.Property<DateTimeOffset?>("ResolvedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolved_at");

                    b.Property<string>("ResolvedById")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("resolved_by_id");

                    b.Property<string>("ResolvedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("resolved_by_name");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("scope");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("WindowEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_end");

                    b.Property<DateTimeOffset>("WindowStart")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("window_start");

                    b.HasKey("Id")
                        .HasName("pk_problem_suggestions");

                    b.HasIndex("CategoryId")
                        .IsUnique()
                        .HasDatabaseName("ix_problem_suggestions_open_category")
                        .HasFilter("status = 'Open' AND category_id IS NOT NULL");

                    b.HasIndex("CiId")
                        .IsUnique()
                        .HasDatabaseName("ix_problem_suggestions_open_ci")
                        .HasFilter("status = 'Open' AND ci_id IS NOT NULL");

                    b.HasIndex("CreatedProblemId")
                        .HasDatabaseName("ix_problem_suggestions_created_problem_id");

                    b.HasIndex("Status", "DetectedAt")
                        .HasDatabaseName("ix_problem_suggestions_status_detected_at");

                    b.ToTable("problem_suggestions", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.SlaPolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CalendarId")
                        .HasColumnType("uuid")
                        .HasColumnName("calendar_id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("priority");

                    b.Property<int>("ResolutionTargetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("resolution_target_minutes");

                    b.Property<int>("ResponseTargetMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("response_target_minutes");

                    b.Property<int>("WarningPercent")
                        .HasColumnType("integer")
                        .HasColumnName("warning_percent");

                    b.HasKey("Id")
                        .HasName("pk_sla_policies");

                    b.HasIndex("CalendarId")
                        .HasDatabaseName("ix_sla_policies_calendar_id");

                    b.HasIndex("Priority", "Category", "IsActive")
                        .HasDatabaseName("ix_sla_policies_priority_category_is_active");

                    b.ToTable("sla_policies", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.Team", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_teams");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_teams_name");

                    b.ToTable("teams", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TeamMember", b =>
                {
                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.Property<string>("TechnicianId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("technician_id");

                    b.Property<DateTimeOffset>("AddedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("added_at");

                    b.HasKey("TeamId", "TechnicianId")
                        .HasName("pk_team_members");

                    b.ToTable("team_members", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.Ticket", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssignedTechnicianId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("assigned_technician_id");

                    b.Property<Guid?>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("description");

                    b.Property<string>("Impact")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("impact");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("priority");

                    b.Property<Guid?>("QueueId")
                        .HasColumnType("uuid")
                        .HasColumnName("queue_id");

                    b.Property<string>("RequesterDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("requester_display_name");

                    b.Property<string>("RequesterEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("requester_email");

                    b.Property<string>("RequesterId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("requester_id");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("setweight(to_tsvector('english', coalesce(title, '')), 'A')\n|| setweight(to_tsvector('english', coalesce(requester_display_name, '')), 'B')\n|| setweight(to_tsvector('english', coalesce(description, '')), 'C')", true);

                    b.Property<long>("SequenceNumber")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("sequence_number");

                    NpgsqlPropertyBuilderExtensions.UseIdentityAlwaysColumn(b.Property<long>("SequenceNumber"));

                    b.Property<Guid>("StatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasDefaultValue(new Guid("10000000-0000-0000-0000-000000000001"))
                        .HasColumnName("status_id");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("title");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Urgency")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("urgency");

                    b.HasKey("Id")
                        .HasName("pk_tickets");

                    b.HasIndex("AssignedTechnicianId")
                        .HasDatabaseName("ix_tickets_assigned_technician_id");

                    b.HasIndex("CategoryId")
                        .HasDatabaseName("ix_tickets_category_id");

                    b.HasIndex("QueueId")
                        .HasDatabaseName("ix_tickets_queue_id");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_tickets_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("SequenceNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_tickets_sequence_number");

                    b.HasIndex("StatusId")
                        .HasDatabaseName("ix_tickets_status_id");

                    b.ToTable("tickets", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketAssignmentHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_id");

                    b.Property<string>("FromTechnicianId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("from_technician_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid>("QueueId")
                        .HasColumnType("uuid")
                        .HasColumnName("queue_id");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<string>("ToTechnicianId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("to_technician_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_assignment_history");

                    b.HasIndex("QueueId")
                        .HasDatabaseName("ix_ticket_assignment_history_queue_id");

                    b.HasIndex("TicketId", "OccurredAt")
                        .HasDatabaseName("ix_ticket_assignment_history_ticket_id_occurred_at");

                    b.ToTable("ticket_assignment_history", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketAttachment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("content_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("file_name");

                    b.Property<string>("ObjectKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("object_key");

                    b.Property<long>("Size")
                        .HasColumnType("bigint")
                        .HasColumnName("size");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<string>("UploadedById")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("uploaded_by_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_attachments");

                    b.HasIndex("ObjectKey")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_attachments_object_key");

                    b.HasIndex("TicketId", "CreatedAt")
                        .HasDatabaseName("ix_ticket_attachments_ticket_id_created_at");

                    b.ToTable("ticket_attachments", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uuid")
                        .HasColumnName("parent_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.HasKey("Id")
                        .HasName("pk_ticket_categories");

                    b.HasIndex("IsActive", "SortOrder")
                        .HasDatabaseName("ix_ticket_categories_is_active_sort_order");

                    b.HasIndex("ParentId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_categories_parent_id_name");

                    b.ToTable("ticket_categories", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketCiLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CiId")
                        .HasColumnType("uuid")
                        .HasColumnName("ci_id");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.Property<string>("LinkedById")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("linked_by_id");

                    b.Property<string>("LinkedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("linked_by_name");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_ci_links");

                    b.HasIndex("CiId")
                        .HasDatabaseName("ix_ticket_ci_links_ci_id");

                    b.HasIndex("TicketId", "CiId")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_ci_links_ticket_id_ci_id");

                    b.ToTable("ticket_ci_links", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketComment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("author_display_name");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("author_id");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("body");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsInternal")
                        .HasColumnType("boolean")
                        .HasColumnName("is_internal");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasAnnotation("Npgsql:TsVectorConfig", "english")
                        .HasAnnotation("Npgsql:TsVectorProperties", new[] { "Body" });

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_comments");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_ticket_comments_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("TicketId", "CreatedAt")
                        .HasDatabaseName("ix_ticket_comments_ticket_id_created_at");

                    b.ToTable("ticket_comments", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketCustomField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.PrimitiveCollection<List<string>>("Options")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("options");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_ticket_custom_fields");

                    b.HasIndex("CategoryId", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_custom_fields_category_id_key");

                    b.ToTable("ticket_custom_fields", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketCustomFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("field_id");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_ticket_custom_field_values");

                    b.HasIndex("FieldId")
                        .HasDatabaseName("ix_ticket_custom_field_values_field_id");

                    b.HasIndex("TicketId", "FieldId")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_custom_field_values_ticket_id_field_id");

                    b.ToTable("ticket_custom_field_values", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketEmail", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("MessageId")
                        .IsRequired()
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)")
                        .HasColumnName("message_id");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<string>("Sender")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("sender");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(998)
                        .HasColumnType("character varying(998)")
                        .HasColumnName("subject");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_emails");

                    b.HasIndex("MessageId")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_emails_message_id");

                    b.HasIndex("TicketId")
                        .HasDatabaseName("ix_ticket_emails_ticket_id");

                    b.ToTable("ticket_emails", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketKbArticle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("ArticleId")
                        .HasColumnType("uuid")
                        .HasColumnName("article_id");

                    b.Property<DateTimeOffset>("LinkedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("linked_at");

                    b.Property<string>("LinkedById")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("linked_by_id");

                    b.Property<string>("LinkedByName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("linked_by_name");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_kb_articles");

                    b.HasIndex("ArticleId")
                        .HasDatabaseName("ix_ticket_kb_articles_article_id");

                    b.HasIndex("TicketId", "ArticleId")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_kb_articles_ticket_id_article_id");

                    b.ToTable("ticket_kb_articles", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketQueue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("LastAssignedTechnicianId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("last_assigned_technician_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("TeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("team_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_queues");

                    b.HasIndex("TeamId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_queues_team_id_name");

                    b.ToTable("ticket_queues", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketSla", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<double>("AccumulatedBusinessSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("accumulated_business_seconds");

                    b.Property<DateTimeOffset?>("ActiveSince")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("active_since");

                    b.Property<Guid>("PolicyId")
                        .HasColumnType("uuid")
                        .HasColumnName("policy_id");

                    b.Property<bool>("ResolutionBreached")
                        .HasColumnType("boolean")
                        .HasColumnName("resolution_breached");

                    b.Property<DateTimeOffset?>("ResolutionCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("resolution_completed_at");

                    b.Property<bool>("ResolutionWarningRaised")
                        .HasColumnType("boolean")
                        .HasColumnName("resolution_warning_raised");

                    b.Property<bool>("ResponseBreached")
                        .HasColumnType("boolean")
                        .HasColumnName("response_breached");

                    b.Property<double?>("ResponseBusinessSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("response_business_seconds");

                    b.Property<DateTimeOffset?>("ResponseCompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("response_completed_at");

                    b.Property<bool>("ResponseWarningRaised")
                        .HasColumnType("boolean")
                        .HasColumnName("response_warning_raised");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_slas");

                    b.HasIndex("PolicyId")
                        .HasDatabaseName("ix_ticket_slas_policy_id");

                    b.HasIndex("TicketId")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_slas_ticket_id");

                    b.ToTable("ticket_slas", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketStatus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("name");

                    b.Property<bool>("RequiresResolutionNote")
                        .HasColumnType("boolean")
                        .HasColumnName("requires_resolution_note");

                    b.HasKey("Id")
                        .HasName("pk_ticket_statuses");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_statuses_name");

                    b.ToTable("ticket_statuses", "helpdesk");

                    b.HasData(
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000001"),
                            DisplayOrder = 1,
                            Name = "New",
                            RequiresResolutionNote = false
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000002"),
                            DisplayOrder = 2,
                            Name = "Triage",
                            RequiresResolutionNote = false
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000003"),
                            DisplayOrder = 3,
                            Name = "InProgress",
                            RequiresResolutionNote = false
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000004"),
                            DisplayOrder = 4,
                            Name = "Pending",
                            RequiresResolutionNote = false
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000005"),
                            DisplayOrder = 5,
                            Name = "Resolved",
                            RequiresResolutionNote = true
                        },
                        new
                        {
                            Id = new Guid("10000000-0000-0000-0000-000000000006"),
                            DisplayOrder = 6,
                            Name = "Closed",
                            RequiresResolutionNote = false
                        });
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketStatusTransition", b =>
                {
                    b.Property<Guid>("FromStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_status_id");

                    b.Property<Guid>("ToStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_status_id");

                    b.HasKey("FromStatusId", "ToStatusId")
                        .HasName("pk_ticket_status_transitions");

                    b.HasIndex("ToStatusId")
                        .HasDatabaseName("ix_ticket_status_transitions_to_status_id");

                    b.ToTable("ticket_status_transitions", "helpdesk");

                    b.HasData(
                        new
                        {
                            FromStatusId = new Guid("10000000-0000-0000-0000-000000000001"),
                            ToStatusId = new Guid("10000000-0000-0000-0000-000000000002")
                        },
                        new
                        {
                            FromStatusId = new Guid("10000000-0000-0000-0000-000000000002"),
                            ToStatusId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            FromStatusId = new Guid("10000000-0000-0000-0000-000000000003"),
                            ToStatusId = new Guid("10000000-0000-0000-0000-000000000004")
                        },
                        new
                        {
                            FromStatusId = new Guid("10000000-0000-0000-0000-000000000004"),
                            ToStatusId = new Guid("10000000-0000-0000-0000-000000000003")
                        },
                        new
                        {
                            FromStatusId = new Guid("10000000-0000-0000-0000-000000000004"),
                            ToStatusId = new Guid("10000000-0000-0000-0000-000000000005")
                        },
                        new
                        {
                            FromStatusId = new Guid("10000000-0000-0000-0000-000000000005"),
                            ToStatusId = new Guid("10000000-0000-0000-0000-000000000006")
                        });
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketTransitionHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("FromStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_status_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ResolutionNote")
                        .HasMaxLength(10000)
                        .HasColumnType("character varying(10000)")
                        .HasColumnName("resolution_note");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.Property<Guid>("ToStatusId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_status_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_transition_history");

                    b.HasIndex("FromStatusId")
                        .HasDatabaseName("ix_ticket_transition_history_from_status_id");

                    b.HasIndex("ToStatusId")
                        .HasDatabaseName("ix_ticket_transition_history_to_status_id");

                    b.HasIndex("TicketId", "OccurredAt")
                        .HasDatabaseName("ix_ticket_transition_history_ticket_id_occurred_at");

                    b.ToTable("ticket_transition_history", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketView", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("FilterJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("filter_json");

                    b.Property<bool>("IsShared")
                        .HasColumnType("boolean")
                        .HasColumnName("is_shared");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerDisplayName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("owner_display_name");

                    b.Property<string>("OwnerId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("owner_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_ticket_views");

                    b.HasIndex("IsShared")
                        .HasDatabaseName("ix_ticket_views_is_shared");

                    b.HasIndex("OwnerId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_ticket_views_owner_id_name");

                    b.ToTable("ticket_views", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketWorklog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AuthorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("author_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Minutes")
                        .HasColumnType("integer")
                        .HasColumnName("minutes");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<Guid>("TicketId")
                        .HasColumnType("uuid")
                        .HasColumnName("ticket_id");

                    b.HasKey("Id")
                        .HasName("pk_ticket_worklogs");

                    b.HasIndex("TicketId", "CreatedAt")
                        .HasDatabaseName("ix_ticket_worklogs_ticket_id_created_at");

                    b.ToTable("ticket_worklogs", "helpdesk");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.AlertTicket", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_alert_tickets_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.KbArticle", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.TicketCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_kb_articles_ticket_categories_category_id");

                    b.HasOne("Modules.Helpdesk.Data.Problem", "Problem")
                        .WithMany()
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_kb_articles_problems_problem_id");

                    b.Navigation("Category");

                    b.Navigation("Problem");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.KbArticleRevision", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.KbArticle", "Article")
                        .WithMany("Revisions")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_kb_article_revisions_kb_articles_article_id");

                    b.Navigation("Article");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.Problem", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.TicketCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_problems_ticket_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.ProblemIncident", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.Problem", "Problem")
                        .WithMany("Incidents")
                        .HasForeignKey("ProblemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_incidents_problems_problem_id");

                    b.HasOne("Modules.Helpdesk.Data.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_problem_incidents_tickets_ticket_id");

                    b.Navigation("Problem");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.ProblemSuggestion", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.TicketCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_problem_suggestions_ticket_categories_category_id");

                    b.HasOne("Modules.Helpdesk.Data.Problem", "CreatedProblem")
                        .WithMany()
                        .HasForeignKey("CreatedProblemId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_problem_suggestions_problems_created_problem_id");

                    b.Navigation("Category");

                    b.Navigation("CreatedProblem");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.SlaPolicy", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.BusinessHoursCalendar", "Calendar")
                        .WithMany()
                        .HasForeignKey("CalendarId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sla_policies_business_hours_calendars_calendar_id");

                    b.Navigation("Calendar");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TeamMember", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.Team", "Team")
                        .WithMany("Members")
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_team_members_teams_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.Ticket", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.TicketCategory", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tickets_ticket_categories_category_id");

                    b.HasOne("Modules.Helpdesk.Data.TicketQueue", "Queue")
                        .WithMany()
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_tickets_ticketqueues_queue_id");

                    b.HasOne("Modules.Helpdesk.Data.TicketStatus", "Status")
                        .WithMany()
                        .HasForeignKey("StatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_tickets_ticket_statuses_status_id");

                    b.Navigation("Category");

                    b.Navigation("Queue");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketAssignmentHistory", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.TicketQueue", "Queue")
                        .WithMany()
                        .HasForeignKey("QueueId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_assignment_history_ticketqueues_queue_id");

                    b.HasOne("Modules.Helpdesk.Data.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_assignment_history_tickets_ticket_id");

                    b.Navigation("Queue");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketAttachment", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_attachments_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketCategory", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.TicketCategory", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ticket_categories_ticket_categories_parent_id");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketCiLink", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_ci_links_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketComment", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_comments_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketCustomField", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.TicketCategory", "Category")
                        .WithMany("Fields")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_custom_fields_ticket_categories_category_id");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketCustomFieldValue", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.TicketCustomField", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_custom_field_values_ticket_custom_fields_field_id");

                    b.HasOne("Modules.Helpdesk.Data.Ticket", "Ticket")
                        .WithMany("CustomFieldValues")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_custom_field_values_tickets_ticket_id");

                    b.Navigation("Field");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketEmail", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_emails_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketKbArticle", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.KbArticle", "Article")
                        .WithMany()
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_kb_articles_kb_articles_article_id");

                    b.HasOne("Modules.Helpdesk.Data.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_kb_articles_tickets_ticket_id");

                    b.Navigation("Article");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketQueue", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.Team", "Team")
                        .WithMany()
                        .HasForeignKey("TeamId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_queues_teams_team_id");

                    b.Navigation("Team");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketSla", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.SlaPolicy", "Policy")
                        .WithMany()
                        .HasForeignKey("PolicyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_slas_sla_policies_policy_id");

                    b.HasOne("Modules.Helpdesk.Data.Ticket", "Ticket")
                        .WithOne()
                        .HasForeignKey("Modules.Helpdesk.Data.TicketSla", "TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_slas_tickets_ticket_id");

                    b.Navigation("Policy");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketStatusTransition", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.TicketStatus", "FromStatus")
                        .WithMany()
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_status_transitions_ticket_statuses_from_status_id");

                    b.HasOne("Modules.Helpdesk.Data.TicketStatus", "ToStatus")
                        .WithMany()
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_status_transitions_ticket_statuses_to_status_id");

                    b.Navigation("FromStatus");

                    b.Navigation("ToStatus");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketTransitionHistory", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.TicketStatus", "FromStatus")
                        .WithMany()
                        .HasForeignKey("FromStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_transition_history_ticket_statuses_from_status_id");

                    b.HasOne("Modules.Helpdesk.Data.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_transition_history_tickets_ticket_id");

                    b.HasOne("Modules.Helpdesk.Data.TicketStatus", "ToStatus")
                        .WithMany()
                        .HasForeignKey("ToStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_transition_history_ticket_statuses_to_status_id");

                    b.Navigation("FromStatus");

                    b.Navigation("Ticket");

                    b.Navigation("ToStatus");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketWorklog", b =>
                {
                    b.HasOne("Modules.Helpdesk.Data.Ticket", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ticket_worklogs_tickets_ticket_id");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.KbArticle", b =>
                {
                    b.Navigation("Revisions");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.Problem", b =>
                {
                    b.Navigation("Incidents");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.Team", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.Ticket", b =>
                {
                    b.Navigation("CustomFieldValues");
                });

            modelBuilder.Entity("Modules.Helpdesk.Data.TicketCategory", b =>
                {
                    b.Navigation("Children");

                    b.Navigation("Fields");
                });
#pragma warning restore 612, 618
        }
    }
}
