// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Assets.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using NpgsqlTypes;

#nullable disable

namespace Modules.Assets.Data.Migrations
{
    [DbContext(typeof(AssetsDbContext))]
    [Migration("20260816223734_WP54_GlobalSearch")]
    partial class WP54_GlobalSearch
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("assets")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Assets.Data.CiAssignmentEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("action");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("CiId")
                        .HasColumnType("uuid")
                        .HasColumnName("ci_id");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("department_name");

                    b.Property<string>("FromOwnerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("from_owner_name");

                    b.Property<Guid?>("FromOwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("from_owner_user_id");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("SiteName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("site_name");

                    b.Property<string>("ToOwnerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("to_owner_name");

                    b.Property<Guid?>("ToOwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("to_owner_user_id");

                    b.HasKey("Id")
                        .HasName("pk_ci_assignments");

                    b.HasIndex("CiId", "OccurredAt")
                        .HasDatabaseName("ix_ci_assignments_ci_id_occurred_at");

                    b.ToTable("ci_assignments", "assets");
                });

            modelBuilder.Entity("Modules.Assets.Data.CiCustomField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CiType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ci_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.PrimitiveCollection<List<string>>("Options")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("options");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_ci_custom_field_definitions");

                    b.HasIndex("CiType", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_ci_custom_field_definitions_ci_type_key");

                    b.ToTable("ci_custom_field_definitions", "assets");
                });

            modelBuilder.Entity("Modules.Assets.Data.CiCustomFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CiId")
                        .HasColumnType("uuid")
                        .HasColumnName("ci_id");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("field_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_ci_custom_field_values");

                    b.HasIndex("FieldId")
                        .HasDatabaseName("ix_ci_custom_field_values_field_id");

                    b.HasIndex("CiId", "FieldId")
                        .IsUnique()
                        .HasDatabaseName("ix_ci_custom_field_values_ci_id_field_id");

                    b.ToTable("ci_custom_field_values", "assets");
                });

            modelBuilder.Entity("Modules.Assets.Data.CiDependencyHop", b =>
                {
                    b.Property<Guid>("CiId")
                        .HasColumnType("uuid")
                        .HasColumnName("ci_id");

                    b.Property<Guid>("DependsOnCiId")
                        .HasColumnType("uuid")
                        .HasColumnName("depends_on_ci_id");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("Modules.Assets.Data.CiDiscoveryFacts", b =>
                {
                    b.Property<Guid>("CiId")
                        .HasColumnType("uuid")
                        .HasColumnName("ci_id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("address");

                    b.Property<string>("DiscoveryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("discovery_name");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("Hostname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hostname");

                    b.Property<Guid>("LastScanId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_scan_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("NeighboursJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("neighbours_json");

                    b.Property<string>("OpenPortsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("open_ports_json");

                    b.Property<bool>("RespondedToPing")
                        .HasColumnType("boolean")
                        .HasColumnName("responded_to_ping");

                    b.Property<string>("ScanProfileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scan_profile_name");

                    b.Property<int>("SightingCount")
                        .HasColumnType("integer")
                        .HasColumnName("sighting_count");

                    b.Property<string>("SysContact")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sys_contact");

                    b.Property<string>("SysDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("sys_description");

                    b.Property<string>("SysLocation")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sys_location");

                    b.Property<string>("SysName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sys_name");

                    b.Property<string>("SysObjectId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sys_object_id");

                    b.Property<double?>("UptimeSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("uptime_seconds");

                    b.HasKey("CiId")
                        .HasName("pk_ci_discovery_facts");

                    b.ToTable("ci_discovery_facts", "assets");
                });

            modelBuilder.Entity("Modules.Assets.Data.CiGraphHop", b =>
                {
                    b.Property<Guid>("CiId")
                        .HasColumnType("uuid")
                        .HasColumnName("ci_id");

                    b.Property<int>("Depth")
                        .HasColumnType("integer")
                        .HasColumnName("depth");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("Modules.Assets.Data.CiLifecycleHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ActorId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("actor_id");

                    b.Property<Guid>("CiId")
                        .HasColumnType("uuid")
                        .HasColumnName("ci_id");

                    b.Property<string>("FromState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("from_state");

                    b.Property<string>("Note")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("ToState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("to_state");

                    b.HasKey("Id")
                        .HasName("pk_ci_lifecycle_history");

                    b.HasIndex("CiId", "OccurredAt")
                        .HasDatabaseName("ix_ci_lifecycle_history_ci_id_occurred_at");

                    b.ToTable("ci_lifecycle_history", "assets");
                });

            modelBuilder.Entity("Modules.Assets.Data.CiLifecycleTransition", b =>
                {
                    b.Property<string>("FromState")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("from_state");

                    b.Property<string>("ToState")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("to_state");

                    b.HasKey("FromState", "ToState")
                        .HasName("pk_ci_lifecycle_transitions");

                    b.ToTable("ci_lifecycle_transitions", "assets");

                    b.HasData(
                        new
                        {
                            FromState = "Ordered",
                            ToState = "InStock"
                        },
                        new
                        {
                            FromState = "InStock",
                            ToState = "Deployed"
                        },
                        new
                        {
                            FromState = "InStock",
                            ToState = "InRepair"
                        },
                        new
                        {
                            FromState = "InStock",
                            ToState = "Retired"
                        },
                        new
                        {
                            FromState = "Deployed",
                            ToState = "InStock"
                        },
                        new
                        {
                            FromState = "Deployed",
                            ToState = "InRepair"
                        },
                        new
                        {
                            FromState = "Deployed",
                            ToState = "Retired"
                        },
                        new
                        {
                            FromState = "InRepair",
                            ToState = "Deployed"
                        },
                        new
                        {
                            FromState = "InRepair",
                            ToState = "InStock"
                        },
                        new
                        {
                            FromState = "InRepair",
                            ToState = "Retired"
                        },
                        new
                        {
                            FromState = "Retired",
                            ToState = "Disposed"
                        });
                });

            modelBuilder.Entity("Modules.Assets.Data.CiRelationship", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid>("SourceCiId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_ci_id");

                    b.Property<Guid>("TargetCiId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_ci_id");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_ci_relationships");

                    b.HasIndex("SourceCiId")
                        .HasDatabaseName("ix_ci_relationships_source_ci_id");

                    b.HasIndex("TargetCiId")
                        .HasDatabaseName("ix_ci_relationships_target_ci_id");

                    b.HasIndex("SourceCiId", "TargetCiId", "Type")
                        .IsUnique()
                        .HasDatabaseName("ix_ci_relationships_source_ci_id_target_ci_id_type");

                    b.ToTable("ci_relationships", "assets");
                });

            modelBuilder.Entity("Modules.Assets.Data.ConfigurationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetTag")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("asset_tag");

                    b.Property<DateTimeOffset?>("AssignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("assigned_at");

                    b.Property<string>("CiType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ci_type");

                    b.Property<Guid?>("ContractId")
                        .HasColumnType("uuid")
                        .HasColumnName("contract_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("DepartmentId")
                        .HasColumnType("uuid")
                        .HasColumnName("department_id");

                    b.Property<string>("DepartmentName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("department_name");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LifecycleState")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("lifecycle_state");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("owner_name");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnName("purchase_date");

                    b.Property<NpgsqlTsVector>("SearchVector")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("tsvector")
                        .HasColumnName("search_vector")
                        .HasComputedColumnSql("setweight(to_tsvector('english', coalesce(name, '') || ' ' || coalesce(asset_tag, '')\n    || ' ' || coalesce(serial_number, '')), 'A')\n|| setweight(to_tsvector('english', coalesce(server_hostname, '') || ' '\n    || coalesce(virtual_hostname, '') || ' ' || coalesce(management_ip, '')), 'B')\n|| setweight(to_tsvector('english', coalesce(description, '')), 'C')", true);

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("serial_number");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("SiteName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("site_name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateOnly?>("WarrantyExpiresAt")
                        .HasColumnType("date")
                        .HasColumnName("warranty_expires_at");

                    b.HasKey("Id")
                        .HasName("pk_cis");

                    b.HasIndex("AssetTag")
                        .IsUnique()
                        .HasDatabaseName("ix_cis_asset_tag")
                        .HasFilter("asset_tag IS NOT NULL");

                    b.HasIndex("ContractId")
                        .HasDatabaseName("ix_cis_contract_id");

                    b.HasIndex("DepartmentId")
                        .HasDatabaseName("ix_cis_department_id");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_cis_is_active");

                    b.HasIndex("LifecycleState")
                        .HasDatabaseName("ix_cis_lifecycle_state");

                    b.HasIndex("OwnerUserId")
                        .HasDatabaseName("ix_cis_owner_user_id");

                    b.HasIndex("SearchVector")
                        .HasDatabaseName("ix_cis_search_vector");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("SearchVector"), "GIN");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_cis_serial_number")
                        .HasFilter("serial_number IS NOT NULL");

                    b.HasIndex("SiteId")
                        .HasDatabaseName("ix_cis_site_id");

                    b.HasIndex("WarrantyExpiresAt")
                        .HasDatabaseName("ix_cis_warranty_expires_at");

                    b.HasIndex("CiType", "Name")
                        .HasDatabaseName("ix_cis_ci_type_name");

                    b.ToTable("cis", "assets");

                    b.HasDiscriminator<string>("CiType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Modules.Assets.Data.Contract", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AutoRenews")
                        .HasColumnType("boolean")
                        .HasColumnName("auto_renews");

                    b.Property<string>("ContractNumber")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("contract_number");

                    b.Property<decimal?>("Cost")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("cost");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("end_date");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("OwnerEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("owner_email");

                    b.Property<string>("OwnerName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("owner_name");

                    b.Property<Guid?>("OwnerUserId")
                        .HasColumnType("uuid")
                        .HasColumnName("owner_user_id");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("start_date");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("VendorId")
                        .HasColumnType("uuid")
                        .HasColumnName("vendor_id");

                    b.HasKey("Id")
                        .HasName("pk_contracts");

                    b.HasIndex("ContractNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_contracts_contract_number");

                    b.HasIndex("EndDate")
                        .HasDatabaseName("ix_contracts_end_date");

                    b.HasIndex("VendorId")
                        .HasDatabaseName("ix_contracts_vendor_id");

                    b.ToTable("contracts", "assets");
                });

            modelBuilder.Entity("Modules.Assets.Data.ContractNotification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("message");

                    b.Property<string>("Recipient")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("recipient");

                    b.Property<DateTimeOffset>("SentAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sent_at");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("subject");

                    b.Property<Guid>("SubjectId")
                        .HasColumnType("uuid")
                        .HasColumnName("subject_id");

                    b.Property<string>("SubjectName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("subject_name");

                    b.Property<int>("ThresholdDays")
                        .HasColumnType("integer")
                        .HasColumnName("threshold_days");

                    b.HasKey("Id")
                        .HasName("pk_contract_notifications");

                    b.HasIndex("SentAt")
                        .HasDatabaseName("ix_contract_notifications_sent_at");

                    b.HasIndex("Subject", "SubjectId", "DueDate", "ThresholdDays")
                        .IsUnique()
                        .HasDatabaseName("ix_contract_notifications_subject_subject_id_due_date_threshol~");

                    b.ToTable("contract_notifications", "assets");
                });

            modelBuilder.Entity("Modules.Assets.Data.DiscoveredDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("address");

                    b.Property<Guid?>("CiId")
                        .HasColumnType("uuid")
                        .HasColumnName("ci_id");

                    b.Property<string>("ContenderCiIdsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("contender_ci_ids_json");

                    b.Property<string>("DiscoveryName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("discovery_name");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("Hostname")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("hostname");

                    b.Property<string>("IdentityKey")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("identity_key");

                    b.Property<Guid>("LastScanId")
                        .HasColumnType("uuid")
                        .HasColumnName("last_scan_id");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("MatchRule")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("match_rule");

                    b.Property<string>("NeighboursJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("neighbours_json");

                    b.Property<string>("OpenPortsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("open_ports_json");

                    b.Property<bool>("RespondedToPing")
                        .HasColumnType("boolean")
                        .HasColumnName("responded_to_ping");

                    b.Property<string>("ReviewNote")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("review_note");

                    b.Property<DateTimeOffset?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("reviewed_by");

                    b.Property<Guid>("ScanProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("scan_profile_id");

                    b.Property<string>("ScanProfileName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scan_profile_name");

                    b.Property<int>("SightingCount")
                        .HasColumnType("integer")
                        .HasColumnName("sighting_count");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("SysContact")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sys_contact");

                    b.Property<string>("SysDescription")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("sys_description");

                    b.Property<string>("SysLocation")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sys_location");

                    b.Property<string>("SysName")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sys_name");

                    b.Property<string>("SysObjectId")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("sys_object_id");

                    b.Property<double?>("UptimeSeconds")
                        .HasColumnType("double precision")
                        .HasColumnName("uptime_seconds");

                    b.HasKey("Id")
                        .HasName("pk_discovered_devices");

                    b.HasIndex("Address")
                        .HasDatabaseName("ix_discovered_devices_address");

                    b.HasIndex("CiId")
                        .HasDatabaseName("ix_discovered_devices_ci_id");

                    b.HasIndex("Hostname")
                        .HasDatabaseName("ix_discovered_devices_hostname");

                    b.HasIndex("IdentityKey")
                        .IsUnique()
                        .HasDatabaseName("ix_discovered_devices_identity_key");

                    b.HasIndex("SysName")
                        .HasDatabaseName("ix_discovered_devices_sys_name");

                    b.HasIndex("Status", "LastSeenAt")
                        .HasDatabaseName("ix_discovered_devices_status_last_seen_at");

                    b.ToTable("discovered_devices", "assets");
                });

            modelBuilder.Entity("Modules.Assets.Data.InstalledSoftware", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CiId")
                        .HasColumnType("uuid")
                        .HasColumnName("ci_id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<string>("IdentityKey")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("identity_key");

                    b.Property<DateOnly?>("InstalledOn")
                        .HasColumnType("date")
                        .HasColumnName("installed_on");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<Guid?>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<string>("RawName")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("raw_name");

                    b.Property<string>("RawPublisher")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("raw_publisher");

                    b.Property<int>("SightingCount")
                        .HasColumnType("integer")
                        .HasColumnName("sighting_count");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source");

                    b.Property<string>("Version")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_installed_software");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_installed_software_product_id");

                    b.HasIndex("RawName")
                        .HasDatabaseName("ix_installed_software_raw_name");

                    b.HasIndex("CiId", "IdentityKey")
                        .IsUnique()
                        .HasDatabaseName("ix_installed_software_ci_id_identity_key");

                    b.ToTable("installed_software", "assets");
                });

            modelBuilder.Entity("Modules.Assets.Data.LicensePool", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Entitlements")
                        .HasColumnType("integer")
                        .HasColumnName("entitlements");

                    b.Property<DateOnly?>("ExpiresAt")
                        .HasColumnType("date")
                        .HasColumnName("expires_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateOnly?>("PurchaseDate")
                        .HasColumnType("date")
                        .HasColumnName("purchase_date");

                    b.Property<string>("Reference")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("reference");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_license_pools");

                    b.HasIndex("ExpiresAt")
                        .HasDatabaseName("ix_license_pools_expires_at");

                    b.HasIndex("ProductId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_license_pools_product_id_name");

                    b.ToTable("license_pools", "assets");
                });

            modelBuilder.Entity("Modules.Assets.Data.PhysicalAuditScan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CiId")
                        .HasColumnType("uuid")
                        .HasColumnName("ci_id");

                    b.Property<string>("CiName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("ci_name");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("code");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("ScannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("scanned_at");

                    b.Property<string>("ScannedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scanned_by");

                    b.Property<Guid>("SessionId")
                        .HasColumnType("uuid")
                        .HasColumnName("session_id");

                    b.HasKey("Id")
                        .HasName("pk_physical_audit_scans");

                    b.HasIndex("CiId")
                        .HasDatabaseName("ix_physical_audit_scans_ci_id");

                    b.HasIndex("SessionId", "CiId")
                        .IsUnique()
                        .HasDatabaseName("ix_physical_audit_scans_session_id_ci_id");

                    b.ToTable("physical_audit_scans", "assets");
                });

            modelBuilder.Entity("Modules.Assets.Data.PhysicalAuditSession", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<string>("ClosedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("closed_by");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("note");

                    b.Property<DateTimeOffset>("OpenedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("opened_at");

                    b.Property<string>("OpenedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("opened_by");

                    b.Property<Guid?>("SiteId")
                        .HasColumnType("uuid")
                        .HasColumnName("site_id");

                    b.Property<string>("SiteName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("site_name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.HasKey("Id")
                        .HasName("pk_physical_audit_sessions");

                    b.HasIndex("Status", "OpenedAt")
                        .HasDatabaseName("ix_physical_audit_sessions_status_opened_at");

                    b.ToTable("physical_audit_sessions", "assets");
                });

            modelBuilder.Entity("Modules.Assets.Data.SoftwareNormalisationRule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("MatchKind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("match_kind");

                    b.Property<string>("Pattern")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)")
                        .HasColumnName("pattern");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("priority");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("uuid")
                        .HasColumnName("product_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_software_normalisation_rules");

                    b.HasIndex("ProductId")
                        .HasDatabaseName("ix_software_normalisation_rules_product_id");

                    b.HasIndex("MatchKind", "Pattern")
                        .IsUnique()
                        .HasDatabaseName("ix_software_normalisation_rules_match_kind_pattern");

                    b.ToTable("software_normalisation_rules", "assets");
                });

            modelBuilder.Entity("Modules.Assets.Data.SoftwareProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Category")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("category");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("Publisher")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("publisher");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_software_products");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_software_products_is_active");

                    b.HasIndex("Publisher", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_software_products_publisher_name");

                    b.ToTable("software_products", "assets");
                });

            modelBuilder.Entity("Modules.Assets.Data.TopologyMap", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_topology_maps");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_topology_maps_name");

                    b.ToTable("topology_maps", "assets");
                });

            modelBuilder.Entity("Modules.Assets.Data.TopologyMapNode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CiId")
                        .HasColumnType("uuid")
                        .HasColumnName("ci_id");

                    b.Property<Guid>("TopologyMapId")
                        .HasColumnType("uuid")
                        .HasColumnName("topology_map_id");

                    b.Property<double>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("x");

                    b.Property<double>("Y")
                        .HasColumnType("double precision")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("pk_topology_map_nodes");

                    b.HasIndex("CiId")
                        .HasDatabaseName("ix_topology_map_nodes_ci_id");

                    b.HasIndex("TopologyMapId", "CiId")
                        .IsUnique()
                        .HasDatabaseName("ix_topology_map_nodes_topology_map_id_ci_id");

                    b.ToTable("topology_map_nodes", "assets");
                });

            modelBuilder.Entity("Modules.Assets.Data.Vendor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(320)
                        .HasColumnType("character varying(320)")
                        .HasColumnName("contact_email");

                    b.Property<string>("ContactName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("contact_name");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("contact_phone");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Website")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("website");

                    b.HasKey("Id")
                        .HasName("pk_vendors");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_vendors_is_active");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_vendors_name");

                    b.ToTable("vendors", "assets");
                });

            modelBuilder.Entity("Modules.Assets.Data.HardwareCi", b =>
                {
                    b.HasBaseType("Modules.Assets.Data.ConfigurationItem");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("model");

                    b.ToTable("cis", "assets");

                    b.HasDiscriminator().HasValue("Hardware");
                });

            modelBuilder.Entity("Modules.Assets.Data.LogicalCi", b =>
                {
                    b.HasBaseType("Modules.Assets.Data.ConfigurationItem");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("purpose");

                    b.Property<string>("ServiceTier")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("service_tier");

                    b.ToTable("cis", "assets");

                    b.HasDiscriminator().HasValue("Logical");
                });

            modelBuilder.Entity("Modules.Assets.Data.NetworkDeviceCi", b =>
                {
                    b.HasBaseType("Modules.Assets.Data.ConfigurationItem");

                    b.Property<string>("ManagementIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("management_ip");

                    b.Property<int>("PortCount")
                        .HasColumnType("integer")
                        .HasColumnName("port_count");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("network_vendor");

                    b.ToTable("cis", "assets");

                    b.HasDiscriminator().HasValue("NetworkDevice");
                });

            modelBuilder.Entity("Modules.Assets.Data.ServerCi", b =>
                {
                    b.HasBaseType("Modules.Assets.Data.ConfigurationItem");

                    b.Property<int>("CpuCores")
                        .HasColumnType("integer")
                        .HasColumnName("cpu_cores");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("server_hostname");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("operating_system");

                    b.Property<int>("RamGb")
                        .HasColumnType("integer")
                        .HasColumnName("server_ram_gb");

                    b.ToTable("cis", "assets");

                    b.HasDiscriminator().HasValue("Server");
                });

            modelBuilder.Entity("Modules.Assets.Data.SoftwareCi", b =>
                {
                    b.HasBaseType("Modules.Assets.Data.ConfigurationItem");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("software_vendor");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.ToTable("cis", "assets");

                    b.HasDiscriminator().HasValue("Software");
                });

            modelBuilder.Entity("Modules.Assets.Data.VirtualCi", b =>
                {
                    b.HasBaseType("Modules.Assets.Data.ConfigurationItem");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("virtual_hostname");

                    b.Property<string>("Hypervisor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("hypervisor");

                    b.Property<int>("RamGb")
                        .HasColumnType("integer")
                        .HasColumnName("virtual_ram_gb");

                    b.Property<int>("VcpuCores")
                        .HasColumnType("integer")
                        .HasColumnName("vcpu_cores");

                    b.ToTable("cis", "assets");

                    b.HasDiscriminator().HasValue("Virtual");
                });

            modelBuilder.Entity("Modules.Assets.Data.CiAssignmentEntry", b =>
                {
                    b.HasOne("Modules.Assets.Data.ConfigurationItem", "Ci")
                        .WithMany()
                        .HasForeignKey("CiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ci_assignments_cis_ci_id");

                    b.Navigation("Ci");
                });

            modelBuilder.Entity("Modules.Assets.Data.CiCustomFieldValue", b =>
                {
                    b.HasOne("Modules.Assets.Data.ConfigurationItem", "Ci")
                        .WithMany("CustomFieldValues")
                        .HasForeignKey("CiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ci_custom_field_values_cis_ci_id");

                    b.HasOne("Modules.Assets.Data.CiCustomField", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ci_custom_field_values_ci_custom_field_definitions_field_id");

                    b.Navigation("Ci");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("Modules.Assets.Data.CiDiscoveryFacts", b =>
                {
                    b.HasOne("Modules.Assets.Data.ConfigurationItem", "Ci")
                        .WithOne()
                        .HasForeignKey("Modules.Assets.Data.CiDiscoveryFacts", "CiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ci_discovery_facts_cis_ci_id");

                    b.Navigation("Ci");
                });

            modelBuilder.Entity("Modules.Assets.Data.CiLifecycleHistory", b =>
                {
                    b.HasOne("Modules.Assets.Data.ConfigurationItem", "Ci")
                        .WithMany()
                        .HasForeignKey("CiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ci_lifecycle_history_cis_ci_id");

                    b.Navigation("Ci");
                });

            modelBuilder.Entity("Modules.Assets.Data.CiRelationship", b =>
                {
                    b.HasOne("Modules.Assets.Data.ConfigurationItem", "SourceCi")
                        .WithMany()
                        .HasForeignKey("SourceCiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ci_relationships_cis_source_ci_id");

                    b.HasOne("Modules.Assets.Data.ConfigurationItem", "TargetCi")
                        .WithMany()
                        .HasForeignKey("TargetCiId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ci_relationships_cis_target_ci_id");

                    b.Navigation("SourceCi");

                    b.Navigation("TargetCi");
                });

            modelBuilder.Entity("Modules.Assets.Data.ConfigurationItem", b =>
                {
                    b.HasOne("Modules.Assets.Data.Contract", "Contract")
                        .WithMany("Cis")
                        .HasForeignKey("ContractId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_cis_contracts_contract_id");

                    b.Navigation("Contract");
                });

            modelBuilder.Entity("Modules.Assets.Data.Contract", b =>
                {
                    b.HasOne("Modules.Assets.Data.Vendor", "Vendor")
                        .WithMany("Contracts")
                        .HasForeignKey("VendorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_contracts_vendors_vendor_id");

                    b.Navigation("Vendor");
                });

            modelBuilder.Entity("Modules.Assets.Data.InstalledSoftware", b =>
                {
                    b.HasOne("Modules.Assets.Data.ConfigurationItem", "Ci")
                        .WithMany()
                        .HasForeignKey("CiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_installed_software_cis_ci_id");

                    b.HasOne("Modules.Assets.Data.SoftwareProduct", "Product")
                        .WithMany("Installs")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_installed_software_software_products_product_id");

                    b.Navigation("Ci");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Modules.Assets.Data.LicensePool", b =>
                {
                    b.HasOne("Modules.Assets.Data.SoftwareProduct", "Product")
                        .WithMany("LicensePools")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_license_pools_software_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Modules.Assets.Data.PhysicalAuditScan", b =>
                {
                    b.HasOne("Modules.Assets.Data.ConfigurationItem", "Ci")
                        .WithMany()
                        .HasForeignKey("CiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_physical_audit_scans_cis_ci_id");

                    b.HasOne("Modules.Assets.Data.PhysicalAuditSession", "Session")
                        .WithMany("Scans")
                        .HasForeignKey("SessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_physical_audit_scans_physical_audit_sessions_session_id");

                    b.Navigation("Ci");

                    b.Navigation("Session");
                });

            modelBuilder.Entity("Modules.Assets.Data.SoftwareNormalisationRule", b =>
                {
                    b.HasOne("Modules.Assets.Data.SoftwareProduct", "Product")
                        .WithMany("Rules")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_software_normalisation_rules_software_products_product_id");

                    b.Navigation("Product");
                });

            modelBuilder.Entity("Modules.Assets.Data.TopologyMapNode", b =>
                {
                    b.HasOne("Modules.Assets.Data.ConfigurationItem", "Ci")
                        .WithMany()
                        .HasForeignKey("CiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_topology_map_nodes_cis_ci_id");

                    b.HasOne("Modules.Assets.Data.TopologyMap", "Map")
                        .WithMany("Nodes")
                        .HasForeignKey("TopologyMapId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_topology_map_nodes_topology_maps_topology_map_id");

                    b.Navigation("Ci");

                    b.Navigation("Map");
                });

            modelBuilder.Entity("Modules.Assets.Data.ConfigurationItem", b =>
                {
                    b.Navigation("CustomFieldValues");
                });

            modelBuilder.Entity("Modules.Assets.Data.Contract", b =>
                {
                    b.Navigation("Cis");
                });

            modelBuilder.Entity("Modules.Assets.Data.PhysicalAuditSession", b =>
                {
                    b.Navigation("Scans");
                });

            modelBuilder.Entity("Modules.Assets.Data.SoftwareProduct", b =>
                {
                    b.Navigation("Installs");

                    b.Navigation("LicensePools");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("Modules.Assets.Data.TopologyMap", b =>
                {
                    b.Navigation("Nodes");
                });

            modelBuilder.Entity("Modules.Assets.Data.Vendor", b =>
                {
                    b.Navigation("Contracts");
                });
#pragma warning restore 612, 618
        }
    }
}
