// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Assets.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Assets.Data.Migrations
{
    [DbContext(typeof(AssetsDbContext))]
    [Migration("20260807051232_WP21_CiRegistry")]
    partial class WP21_CiRegistry
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("assets")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Assets.Data.CiCustomField", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CiType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ci_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean")
                        .HasColumnName("is_required");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("key");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("label");

                    b.PrimitiveCollection<List<string>>("Options")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("options");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_ci_custom_field_definitions");

                    b.HasIndex("CiType", "Key")
                        .IsUnique()
                        .HasDatabaseName("ix_ci_custom_field_definitions_ci_type_key");

                    b.ToTable("ci_custom_field_definitions", "assets");
                });

            modelBuilder.Entity("Modules.Assets.Data.CiCustomFieldValue", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("CiId")
                        .HasColumnType("uuid")
                        .HasColumnName("ci_id");

                    b.Property<Guid>("FieldId")
                        .HasColumnType("uuid")
                        .HasColumnName("field_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("value");

                    b.HasKey("Id")
                        .HasName("pk_ci_custom_field_values");

                    b.HasIndex("FieldId")
                        .HasDatabaseName("ix_ci_custom_field_values_field_id");

                    b.HasIndex("CiId", "FieldId")
                        .IsUnique()
                        .HasDatabaseName("ix_ci_custom_field_values_ci_id_field_id");

                    b.ToTable("ci_custom_field_values", "assets");
                });

            modelBuilder.Entity("Modules.Assets.Data.ConfigurationItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AssetTag")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("asset_tag");

                    b.Property<string>("CiType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("ci_type");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("SerialNumber")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("serial_number");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_cis");

                    b.HasIndex("AssetTag")
                        .IsUnique()
                        .HasDatabaseName("ix_cis_asset_tag")
                        .HasFilter("asset_tag IS NOT NULL");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_cis_is_active");

                    b.HasIndex("SerialNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_cis_serial_number")
                        .HasFilter("serial_number IS NOT NULL");

                    b.HasIndex("CiType", "Name")
                        .HasDatabaseName("ix_cis_ci_type_name");

                    b.ToTable("cis", "assets");

                    b.HasDiscriminator<string>("CiType");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Modules.Assets.Data.HardwareCi", b =>
                {
                    b.HasBaseType("Modules.Assets.Data.ConfigurationItem");

                    b.Property<string>("Manufacturer")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("manufacturer");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("model");

                    b.ToTable("cis", "assets");

                    b.HasDiscriminator().HasValue("Hardware");
                });

            modelBuilder.Entity("Modules.Assets.Data.LogicalCi", b =>
                {
                    b.HasBaseType("Modules.Assets.Data.ConfigurationItem");

                    b.Property<string>("Purpose")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("purpose");

                    b.Property<string>("ServiceTier")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("service_tier");

                    b.ToTable("cis", "assets");

                    b.HasDiscriminator().HasValue("Logical");
                });

            modelBuilder.Entity("Modules.Assets.Data.NetworkDeviceCi", b =>
                {
                    b.HasBaseType("Modules.Assets.Data.ConfigurationItem");

                    b.Property<string>("ManagementIp")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)")
                        .HasColumnName("management_ip");

                    b.Property<int>("PortCount")
                        .HasColumnType("integer")
                        .HasColumnName("port_count");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("network_vendor");

                    b.ToTable("cis", "assets");

                    b.HasDiscriminator().HasValue("NetworkDevice");
                });

            modelBuilder.Entity("Modules.Assets.Data.ServerCi", b =>
                {
                    b.HasBaseType("Modules.Assets.Data.ConfigurationItem");

                    b.Property<int>("CpuCores")
                        .HasColumnType("integer")
                        .HasColumnName("cpu_cores");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("server_hostname");

                    b.Property<string>("OperatingSystem")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("operating_system");

                    b.Property<int>("RamGb")
                        .HasColumnType("integer")
                        .HasColumnName("server_ram_gb");

                    b.ToTable("cis", "assets");

                    b.HasDiscriminator().HasValue("Server");
                });

            modelBuilder.Entity("Modules.Assets.Data.SoftwareCi", b =>
                {
                    b.HasBaseType("Modules.Assets.Data.ConfigurationItem");

                    b.Property<string>("Vendor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("software_vendor");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("version");

                    b.ToTable("cis", "assets");

                    b.HasDiscriminator().HasValue("Software");
                });

            modelBuilder.Entity("Modules.Assets.Data.VirtualCi", b =>
                {
                    b.HasBaseType("Modules.Assets.Data.ConfigurationItem");

                    b.Property<string>("Hostname")
                        .IsRequired()
                        .HasMaxLength(253)
                        .HasColumnType("character varying(253)")
                        .HasColumnName("virtual_hostname");

                    b.Property<string>("Hypervisor")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("hypervisor");

                    b.Property<int>("RamGb")
                        .HasColumnType("integer")
                        .HasColumnName("virtual_ram_gb");

                    b.Property<int>("VcpuCores")
                        .HasColumnType("integer")
                        .HasColumnName("vcpu_cores");

                    b.ToTable("cis", "assets");

                    b.HasDiscriminator().HasValue("Virtual");
                });

            modelBuilder.Entity("Modules.Assets.Data.CiCustomFieldValue", b =>
                {
                    b.HasOne("Modules.Assets.Data.ConfigurationItem", "Ci")
                        .WithMany("CustomFieldValues")
                        .HasForeignKey("CiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ci_custom_field_values_cis_ci_id");

                    b.HasOne("Modules.Assets.Data.CiCustomField", "Field")
                        .WithMany()
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_ci_custom_field_values_ci_custom_field_definitions_field_id");

                    b.Navigation("Ci");

                    b.Navigation("Field");
                });

            modelBuilder.Entity("Modules.Assets.Data.ConfigurationItem", b =>
                {
                    b.Navigation("CustomFieldValues");
                });
#pragma warning restore 612, 618
        }
    }
}
