// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Monitoring.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Monitoring.Data.Migrations
{
    [DbContext(typeof(MonitoringDbContext))]
    [Migration("20260809231051_WP32_PollerHeartbeat")]
    partial class WP32_PollerHeartbeat
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("monitoring")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Monitoring.Data.CheckDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comparison")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("comparison");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<double?>("CriticalThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("critical_threshold");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("interval_seconds");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters_json");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_seconds");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<double?>("WarningThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("warning_threshold");

                    b.HasKey("Id")
                        .HasName("pk_check_definitions");

                    b.HasIndex("DeviceId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_check_definitions_device_id_name");

                    b.ToTable("check_definitions", "monitoring");
                });

            modelBuilder.Entity("Modules.Monitoring.Data.MaintenanceWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AppliesToAllDevices")
                        .HasColumnType("boolean")
                        .HasColumnName("applies_to_all_devices");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_windows");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_maintenance_windows_is_active");

                    b.HasIndex("StartsAt", "EndsAt")
                        .HasDatabaseName("ix_maintenance_windows_starts_at_ends_at");

                    b.ToTable("maintenance_windows", "monitoring");
                });

            modelBuilder.Entity("Modules.Monitoring.Data.MaintenanceWindowDevice", b =>
                {
                    b.Property<Guid>("MaintenanceWindowId")
                        .HasColumnType("uuid")
                        .HasColumnName("maintenance_window_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.HasKey("MaintenanceWindowId", "DeviceId")
                        .HasName("pk_maintenance_window_devices");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_maintenance_window_devices_device_id");

                    b.ToTable("maintenance_window_devices", "monitoring");
                });

            modelBuilder.Entity("Modules.Monitoring.Data.MonitoredDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<Guid>("CiId")
                        .HasColumnType("uuid")
                        .HasColumnName("ci_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("PollerGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("poller_group");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_monitored_devices");

                    b.HasIndex("CiId")
                        .IsUnique()
                        .HasDatabaseName("ix_monitored_devices_ci_id");

                    b.HasIndex("PollerGroup", "IsEnabled")
                        .HasDatabaseName("ix_monitored_devices_poller_group_is_enabled");

                    b.ToTable("monitored_devices", "monitoring");
                });

            modelBuilder.Entity("Modules.Monitoring.Data.MonitoringConfigChange", b =>
                {
                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PollerGroup")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("poller_group");

                    b.HasKey("Version")
                        .HasName("pk_config_changes");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_config_changes_device_id");

                    b.HasIndex("PollerGroup")
                        .HasDatabaseName("ix_config_changes_poller_group");

                    b.ToTable("config_changes", "monitoring");
                });

            modelBuilder.Entity("Modules.Monitoring.Data.Poller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("agent_version");

                    b.Property<int?>("HeartbeatIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("heartbeat_interval_seconds");

                    b.Property<DateTimeOffset?>("HeartbeatMissedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("heartbeat_missed_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTimeOffset?>("LastConfigFetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_config_fetched_at");

                    b.Property<long>("LastConfigVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("last_config_version");

                    b.Property<long>("LastCycleNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_cycle_number");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<DateTimeOffset>("LastRegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_registered_at");

                    b.Property<int>("LastReportedDeviceCount")
                        .HasColumnType("integer")
                        .HasColumnName("last_reported_device_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PollerGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("poller_group");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.HasKey("Id")
                        .HasName("pk_pollers");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_pollers_name");

                    b.HasIndex("IsEnabled", "LastHeartbeatAt")
                        .HasDatabaseName("ix_pollers_is_enabled_last_heartbeat_at");

                    b.ToTable("pollers", "monitoring");
                });

            modelBuilder.Entity("Modules.Monitoring.Data.CheckDefinition", b =>
                {
                    b.HasOne("Modules.Monitoring.Data.MonitoredDevice", "Device")
                        .WithMany("Checks")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_check_definitions_monitored_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Modules.Monitoring.Data.MaintenanceWindowDevice", b =>
                {
                    b.HasOne("Modules.Monitoring.Data.MonitoredDevice", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_window_devices_monitored_devices_device_id");

                    b.HasOne("Modules.Monitoring.Data.MaintenanceWindow", "MaintenanceWindow")
                        .WithMany("Devices")
                        .HasForeignKey("MaintenanceWindowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_window_devices_maintenance_windows_maintenance_~");

                    b.Navigation("Device");

                    b.Navigation("MaintenanceWindow");
                });

            modelBuilder.Entity("Modules.Monitoring.Data.MaintenanceWindow", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("Modules.Monitoring.Data.MonitoredDevice", b =>
                {
                    b.Navigation("Checks");
                });
#pragma warning restore 612, 618
        }
    }
}
