// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Monitoring.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Monitoring.Data.Migrations
{
    [DbContext(typeof(MonitoringDbContext))]
    [Migration("20260813231804_WP45_DeviceInterfaces")]
    partial class WP45_DeviceInterfaces
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("monitoring")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Monitoring.Data.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("AcknowledgedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("acknowledged_at");

                    b.Property<string>("AcknowledgedBy")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("acknowledged_by");

                    b.Property<string>("AcknowledgedByName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("acknowledged_by_name");

                    b.Property<Guid>("CheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("check_id");

                    b.Property<Guid>("CiId")
                        .HasColumnType("uuid")
                        .HasColumnName("ci_id");

                    b.Property<DateTimeOffset?>("ClearedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("cleared_at");

                    b.Property<int>("ConsecutiveBreaches")
                        .HasColumnType("integer")
                        .HasColumnName("consecutive_breaches");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<bool>("IsFlapping")
                        .HasColumnType("boolean")
                        .HasColumnName("is_flapping");

                    b.Property<DateTimeOffset>("LastObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_observed_at");

                    b.Property<double?>("LastValue")
                        .HasColumnType("double precision")
                        .HasColumnName("last_value");

                    b.Property<string>("MetricName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("metric_name");

                    b.Property<string>("PollerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("poller_name");

                    b.Property<DateTimeOffset>("RaisedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("raised_at");

                    b.Property<string>("RuleId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("rule_id");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("severity");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("summary");

                    b.Property<string>("Suppression")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("suppression");

                    b.Property<double?>("Threshold")
                        .HasColumnType("double precision")
                        .HasColumnName("threshold");

                    b.HasKey("Id")
                        .HasName("pk_alerts");

                    b.HasIndex("DeviceId", "RuleId")
                        .IsUnique()
                        .HasDatabaseName("ix_alerts_device_id_rule_id")
                        .HasFilter("status = 'Open'");

                    b.HasIndex("Status", "Severity", "RaisedAt")
                        .HasDatabaseName("ix_alerts_status_severity_raised_at");

                    b.ToTable("alerts", "monitoring");
                });

            modelBuilder.Entity("Modules.Monitoring.Data.CheckDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Comparison")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("comparison");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<Guid?>("CredentialId")
                        .HasColumnType("uuid")
                        .HasColumnName("credential_id");

                    b.Property<double?>("CriticalThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("critical_threshold");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<int?>("FlapThreshold")
                        .HasColumnType("integer")
                        .HasColumnName("flap_threshold");

                    b.Property<int?>("FlapWindowSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("flap_window_seconds");

                    b.Property<double?>("HysteresisPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("hysteresis_percent");

                    b.Property<int>("IntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("interval_seconds");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("ParametersJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("parameters_json");

                    b.Property<int?>("RecoveryCycles")
                        .HasColumnType("integer")
                        .HasColumnName("recovery_cycles");

                    b.Property<int?>("SustainedCycles")
                        .HasColumnType("integer")
                        .HasColumnName("sustained_cycles");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_seconds");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("type");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.Property<double?>("WarningThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("warning_threshold");

                    b.HasKey("Id")
                        .HasName("pk_check_definitions");

                    b.HasIndex("CredentialId")
                        .HasDatabaseName("ix_check_definitions_credential_id")
                        .HasFilter("credential_id is not null");

                    b.HasIndex("DeviceId", "Name")
                        .IsUnique()
                        .HasDatabaseName("ix_check_definitions_device_id_name");

                    b.ToTable("check_definitions", "monitoring");
                });

            modelBuilder.Entity("Modules.Monitoring.Data.DeviceInterface", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<int>("IfIndex")
                        .HasColumnType("integer")
                        .HasColumnName("if_index");

                    b.Property<string>("AdminStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("admin_status");

                    b.Property<string>("Alias")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("alias");

                    b.Property<double?>("BitsInPerSecond")
                        .HasColumnType("double precision")
                        .HasColumnName("bits_in_per_second");

                    b.Property<double?>("BitsOutPerSecond")
                        .HasColumnType("double precision")
                        .HasColumnName("bits_out_per_second");

                    b.Property<Guid>("CheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("check_id");

                    b.Property<double?>("DiscardsInPerSecond")
                        .HasColumnType("double precision")
                        .HasColumnName("discards_in_per_second");

                    b.Property<double?>("DiscardsOutPerSecond")
                        .HasColumnType("double precision")
                        .HasColumnName("discards_out_per_second");

                    b.Property<double?>("ErrorsInPerSecond")
                        .HasColumnType("double precision")
                        .HasColumnName("errors_in_per_second");

                    b.Property<double?>("ErrorsOutPerSecond")
                        .HasColumnType("double precision")
                        .HasColumnName("errors_out_per_second");

                    b.Property<int?>("InterfaceType")
                        .HasColumnType("integer")
                        .HasColumnName("interface_type");

                    b.Property<string>("MacAddress")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("mac_address");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("OperStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("oper_status");

                    b.Property<long?>("SpeedBitsPerSecond")
                        .HasColumnType("bigint")
                        .HasColumnName("speed_bits_per_second");

                    b.Property<double?>("UtilisationPercent")
                        .HasColumnType("double precision")
                        .HasColumnName("utilisation_percent");

                    b.HasKey("DeviceId", "IfIndex")
                        .HasName("pk_device_interfaces");

                    b.ToTable("device_interfaces", "monitoring");
                });

            modelBuilder.Entity("Modules.Monitoring.Data.DeviceInventoryFact", b =>
                {
                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("ObservedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("observed_at");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("value");

                    b.HasKey("DeviceId", "Name")
                        .HasName("pk_device_inventory_facts");

                    b.ToTable("device_inventory_facts", "monitoring");
                });

            modelBuilder.Entity("Modules.Monitoring.Data.DeviceMetric", b =>
                {
                    b.Property<DateTimeOffset>("Time")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("time");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<Guid>("CheckId")
                        .HasColumnType("uuid")
                        .HasColumnName("check_id");

                    b.Property<string>("MetricName")
                        .HasColumnType("text")
                        .HasColumnName("metric_name");

                    b.Property<Guid>("CiId")
                        .HasColumnType("uuid")
                        .HasColumnName("ci_id");

                    b.Property<string>("PollerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("poller_name");

                    b.Property<string>("Unit")
                        .HasColumnType("text")
                        .HasColumnName("unit");

                    b.Property<double>("Value")
                        .HasColumnType("double precision")
                        .HasColumnName("value");

                    b.HasKey("Time", "DeviceId", "CheckId", "MetricName")
                        .HasName("pk_device_metrics");

                    b.HasIndex("DeviceId", "MetricName", "Time")
                        .IsDescending(false, false, true)
                        .HasDatabaseName("ix_device_metrics_device_id_metric_name_time");

                    b.ToTable("device_metrics", "monitoring");
                });

            modelBuilder.Entity("Modules.Monitoring.Data.MaintenanceWindow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("AppliesToAllDevices")
                        .HasColumnType("boolean")
                        .HasColumnName("applies_to_all_devices");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<DateTimeOffset>("EndsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ends_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTimeOffset>("StartsAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("starts_at");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_maintenance_windows");

                    b.HasIndex("IsActive")
                        .HasDatabaseName("ix_maintenance_windows_is_active");

                    b.HasIndex("StartsAt", "EndsAt")
                        .HasDatabaseName("ix_maintenance_windows_starts_at_ends_at");

                    b.ToTable("maintenance_windows", "monitoring");
                });

            modelBuilder.Entity("Modules.Monitoring.Data.MaintenanceWindowDevice", b =>
                {
                    b.Property<Guid>("MaintenanceWindowId")
                        .HasColumnType("uuid")
                        .HasColumnName("maintenance_window_id");

                    b.Property<Guid>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.HasKey("MaintenanceWindowId", "DeviceId")
                        .HasName("pk_maintenance_window_devices");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_maintenance_window_devices_device_id");

                    b.ToTable("maintenance_window_devices", "monitoring");
                });

            modelBuilder.Entity("Modules.Monitoring.Data.MetricBucket", b =>
                {
                    b.Property<double>("AvgValue")
                        .HasColumnType("double precision")
                        .HasColumnName("avg_value");

                    b.Property<DateTimeOffset>("Bucket")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("bucket");

                    b.Property<double>("MaxValue")
                        .HasColumnType("double precision")
                        .HasColumnName("max_value");

                    b.Property<double>("MinValue")
                        .HasColumnType("double precision")
                        .HasColumnName("min_value");

                    b.Property<long>("SampleCount")
                        .HasColumnType("bigint")
                        .HasColumnName("sample_count");

                    b.ToTable((string)null);
                });

            modelBuilder.Entity("Modules.Monitoring.Data.MonitoredDevice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)")
                        .HasColumnName("address");

                    b.Property<Guid>("CiId")
                        .HasColumnType("uuid")
                        .HasColumnName("ci_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("PollerGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("poller_group");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_monitored_devices");

                    b.HasIndex("CiId")
                        .IsUnique()
                        .HasDatabaseName("ix_monitored_devices_ci_id");

                    b.HasIndex("PollerGroup", "IsEnabled")
                        .HasDatabaseName("ix_monitored_devices_poller_group_is_enabled");

                    b.ToTable("monitored_devices", "monitoring");
                });

            modelBuilder.Entity("Modules.Monitoring.Data.MonitoringConfigChange", b =>
                {
                    b.Property<long>("Version")
                        .HasColumnType("bigint")
                        .HasColumnName("version");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uuid")
                        .HasColumnName("device_id");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("entity_type");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("kind");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("PollerGroup")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("poller_group");

                    b.HasKey("Version")
                        .HasName("pk_config_changes");

                    b.HasIndex("DeviceId")
                        .HasDatabaseName("ix_config_changes_device_id");

                    b.HasIndex("PollerGroup")
                        .HasDatabaseName("ix_config_changes_poller_group");

                    b.ToTable("config_changes", "monitoring");
                });

            modelBuilder.Entity("Modules.Monitoring.Data.Poller", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AgentVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("agent_version");

                    b.Property<int?>("HeartbeatIntervalSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("heartbeat_interval_seconds");

                    b.Property<DateTimeOffset?>("HeartbeatMissedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("heartbeat_missed_at");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<DateTimeOffset?>("LastConfigFetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_config_fetched_at");

                    b.Property<long>("LastConfigVersion")
                        .HasColumnType("bigint")
                        .HasColumnName("last_config_version");

                    b.Property<long>("LastCycleNumber")
                        .HasColumnType("bigint")
                        .HasColumnName("last_cycle_number");

                    b.Property<DateTimeOffset?>("LastHeartbeatAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_heartbeat_at");

                    b.Property<DateTimeOffset>("LastRegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_registered_at");

                    b.Property<int>("LastReportedDeviceCount")
                        .HasColumnType("integer")
                        .HasColumnName("last_reported_device_count");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("PollerGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("poller_group");

                    b.Property<DateTimeOffset>("RegisteredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registered_at");

                    b.HasKey("Id")
                        .HasName("pk_pollers");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_pollers_name");

                    b.HasIndex("IsEnabled", "LastHeartbeatAt")
                        .HasDatabaseName("ix_pollers_is_enabled_last_heartbeat_at");

                    b.ToTable("pollers", "monitoring");
                });

            modelBuilder.Entity("Modules.Monitoring.Data.ScanProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("created_by");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<string>("DiscoveryGroup")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("discovery_group");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("integer")
                        .HasColumnName("interval_minutes");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("is_enabled");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<bool>("NeighbourDiscoveryEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("neighbour_discovery_enabled");

                    b.Property<string>("PortsJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ports_json");

                    b.Property<string>("RangesJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("ranges_json");

                    b.Property<bool>("SnmpEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("snmp_enabled");

                    b.Property<int>("TimeoutSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("timeout_seconds");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_scan_profiles");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_scan_profiles_name");

                    b.HasIndex("DiscoveryGroup", "IsEnabled")
                        .HasDatabaseName("ix_scan_profiles_discovery_group_is_enabled");

                    b.ToTable("scan_profiles", "monitoring");
                });

            modelBuilder.Entity("Modules.Monitoring.Data.Alert", b =>
                {
                    b.HasOne("Modules.Monitoring.Data.MonitoredDevice", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_alerts_monitored_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Modules.Monitoring.Data.CheckDefinition", b =>
                {
                    b.HasOne("Modules.Monitoring.Data.MonitoredDevice", "Device")
                        .WithMany("Checks")
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_check_definitions_monitored_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Modules.Monitoring.Data.DeviceInterface", b =>
                {
                    b.HasOne("Modules.Monitoring.Data.MonitoredDevice", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_interfaces_monitored_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Modules.Monitoring.Data.DeviceInventoryFact", b =>
                {
                    b.HasOne("Modules.Monitoring.Data.MonitoredDevice", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_device_inventory_facts_monitored_devices_device_id");

                    b.Navigation("Device");
                });

            modelBuilder.Entity("Modules.Monitoring.Data.MaintenanceWindowDevice", b =>
                {
                    b.HasOne("Modules.Monitoring.Data.MonitoredDevice", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_window_devices_monitored_devices_device_id");

                    b.HasOne("Modules.Monitoring.Data.MaintenanceWindow", "MaintenanceWindow")
                        .WithMany("Devices")
                        .HasForeignKey("MaintenanceWindowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_maintenance_window_devices_maintenance_windows_maintenance_~");

                    b.Navigation("Device");

                    b.Navigation("MaintenanceWindow");
                });

            modelBuilder.Entity("Modules.Monitoring.Data.MaintenanceWindow", b =>
                {
                    b.Navigation("Devices");
                });

            modelBuilder.Entity("Modules.Monitoring.Data.MonitoredDevice", b =>
                {
                    b.Navigation("Checks");
                });
#pragma warning restore 612, 618
        }
    }
}
