using NpgsqlTypes;

namespace Modules.Helpdesk.Data;

/// <summary>
/// A written answer: what the symptom looks like, what causes it, and what to do about it.
/// <para>
/// Owned by Helpdesk because ARCHITECTURE §3's ownership map puts knowledge here beside tickets and
/// problems, and because every read this table gets is asked while somebody is holding a ticket — the
/// agent typing one, the requester about to raise one, the technician closing one.
/// </para>
/// <para>
/// The category is the <see cref="TicketCategory"/> tree rather than a taxonomy of its own. A second tree
/// would mean the same words maintained twice, and the deflection prompt matches on the category the
/// requester has already chosen on the form in front of them.
/// </para>
/// </summary>
public sealed class KbArticle
{
    public Guid Id { get; set; }
    public long SequenceNumber { get; set; }

    public string Title { get; set; } = string.Empty;

    /// <summary>One or two lines shown in a result list and in the deflection prompt, before anything opens.</summary>
    public string Summary { get; set; } = string.Empty;

    /// <summary>The article itself, written as Markdown. Rendered by the browser, never by the server.</summary>
    public string Body { get; set; } = string.Empty;

    /// <summary>
    /// Words people search for that the prose never says — product names, error codes, the thing everybody
    /// calls it. Weighted alongside the summary so a nickname finds the article the manual title hides.
    /// </summary>
    public string? Keywords { get; set; }

    public KbArticleStatus Status { get; set; }

    public Guid? CategoryId { get; set; }
    public TicketCategory? Category { get; set; }

    /// <summary>
    /// The problem this was written from, when it began as WP-5.7's closing prompt. Deliberately not
    /// unique: one problem can honestly produce a how-to and a policy note, and the link is a provenance
    /// record rather than a constraint.
    /// </summary>
    public Guid? ProblemId { get; set; }
    public Problem? Problem { get; set; }

    /// <summary>
    /// Bumped on every content change and stamped onto the revision that change created, so the number on
    /// screen and the number in the history are the same number (WP-5.6's meaning of "versioned").
    /// </summary>
    public int Version { get; set; } = 1;

    public ICollection<KbArticleRevision> Revisions { get; set; } = [];

    /// <summary>Who created the article. Never changes, even after somebody else rewrites every word of it.</summary>
    public string AuthorId { get; set; } = string.Empty;
    public string AuthorName { get; set; } = string.Empty;

    /// <summary>
    /// Who wrote the <em>current</em> version. Distinct from <see cref="AuthorId"/> because a revision has
    /// to record who wrote the content it holds, and the person superseding it is usually not that person.
    /// </summary>
    public string UpdatedById { get; set; } = string.Empty;
    public string UpdatedByName { get; set; } = string.Empty;

    public string? PublishedById { get; set; }
    public string? PublishedByName { get; set; }

    /// <summary>
    /// When it last became visible, and who made it so. Left in place when the article goes back to draft
    /// or is archived — it is the record of when this was last live, which is what somebody asks — so read
    /// it beside <see cref="Status"/> and never instead of it.
    /// </summary>
    public DateTimeOffset? PublishedAt { get; set; }
    public DateTimeOffset? ArchivedAt { get; set; }

    public DateTimeOffset CreatedAt { get; set; }
    public DateTimeOffset UpdatedAt { get; set; }

    /// <summary>
    /// The weighted tsvector both the global search box and the ticket-side suggestions read. Generated by
    /// the database, exactly as the ticket's is (WP-5.4).
    /// </summary>
    public NpgsqlTsVector SearchVector { get; set; } = null!;

    public string Number => $"KB-{SequenceNumber:000000}";
}

/// <summary>
/// Where an article stands. A status with an entry condition, following <see cref="ProblemStatus"/>:
/// <see cref="Published"/> is reachable only once the article has something to say, because a published
/// article that answers nothing is worse than no article — somebody stops looking when they find it.
/// </summary>
public enum KbArticleStatus
{
    /// <summary>Being written. Invisible to end users, and invisible to the deflection prompt.</summary>
    Draft = 1,

    /// <summary>Visible to everybody, including the portal. The only state suggestions and deflection use.</summary>
    Published = 2,

    /// <summary>
    /// Out of date and deliberately kept. Not a delete: an article somebody linked to a resolved ticket is
    /// part of that ticket's record, and history must stay resolvable.
    /// </summary>
    Archived = 3,
}

/// <summary>
/// One earlier state of an article's content.
/// <para>
/// A revision table rather than WP-5.6's "a version number and the audit trail", because the artefact here
/// <em>is</em> the prose: "what did this article say last March" is a question somebody genuinely asks, and
/// answering it out of an audit entry's before/after document is not reading an article.
/// </para>
/// </summary>
public sealed class KbArticleRevision
{
    public Guid Id { get; set; }

    public Guid ArticleId { get; set; }
    public KbArticle Article { get; set; } = null!;

    /// <summary>The article's version number at the moment this content was replaced.</summary>
    public int Version { get; set; }

    public string Title { get; set; } = string.Empty;
    public string Summary { get; set; } = string.Empty;
    public string Body { get; set; } = string.Empty;
    public string? Keywords { get; set; }
    public Guid? CategoryId { get; set; }

    /// <summary>Who wrote this version, and when it stopped being the current one.</summary>
    public string AuthorId { get; set; } = string.Empty;
    public string AuthorName { get; set; } = string.Empty;
    public DateTimeOffset CreatedAt { get; set; }
}

/// <summary>
/// An article attached to a ticket — usually the one that resolved it.
/// <para>
/// A real foreign key on both ends, like <see cref="ProblemIncident"/> and unlike <see cref="TicketCiLink"/>:
/// the ticket and the article are both Helpdesk's, so nothing here crosses a schema.
/// </para>
/// </summary>
public sealed class TicketKbArticle
{
    public Guid Id { get; set; }

    public Guid TicketId { get; set; }
    public Ticket Ticket { get; set; } = null!;

    public Guid ArticleId { get; set; }
    public KbArticle Article { get; set; } = null!;

    public string LinkedById { get; set; } = string.Empty;
    public string LinkedByName { get; set; } = string.Empty;
    public DateTimeOffset LinkedAt { get; set; }
}

/// <summary>
/// The statuses an end user may read, as a set compared with <c>Contains</c> rather than a comparison
/// against a member. Every enum in this solution is stored <c>HasConversion&lt;string&gt;()</c>, so EF
/// translates <c>&lt;</c> and <c>&gt;</c> into comparisons of <em>text</em> — the bug WP-5.6 shipped.
/// </summary>
public static class KbArticleStatuses
{
    /// <summary>What the portal, the deflection prompt and the suggestion list are allowed to see.</summary>
    public static readonly KbArticleStatus[] Readable = [KbArticleStatus.Published];
}
